wget https://www.ast.cam.ac.uk/~tpm40/LAMOST/3500_LAMOST.tar
wget https://www.ast.cam.ac.uk/~tpm40/LAMOST/3750_LAMOST.tar
wget https://www.ast.cam.ac.uk/~tpm40/LAMOST/4000_LAMOST.tar
wget https://www.ast.cam.ac.uk/~tpm40/LAMOST/4250_LAMOST.tar
wget https://www.ast.cam.ac.uk/~tpm40/LAMOST/4500_LAMOST.tar
wget https://www.ast.cam.ac.uk/~tpm40/LAMOST/4750_LAMOST.tar
wget https://www.ast.cam.ac.uk/~tpm40/LAMOST/5000_LAMOST.tar
wget https://www.ast.cam.ac.uk/~tpm40/LAMOST/5250_LAMOST.tar
wget https://www.ast.cam.ac.uk/~tpm40/LAMOST/5500_LAMOST.tar
wget https://www.ast.cam.ac.uk/~tpm40/LAMOST/5750_LAMOST.tar
wget https://www.ast.cam.ac.uk/~tpm40/LAMOST/6000_LAMOST.tar
wget https://www.ast.cam.ac.uk/~tpm40/LAMOST/6250_LAMOST.tar
wget https://www.ast.cam.ac.uk/~tpm40/LAMOST/6500_LAMOST.tar
wget https://www.ast.cam.ac.uk/~tpm40/LAMOST/6750_LAMOST.tar
wget https://www.ast.cam.ac.uk/~tpm40/LAMOST/7000_LAMOST.tar
wget https://www.ast.cam.ac.uk/~tpm40/LAMOST/7250_LAMOST.tar
wget https://www.ast.cam.ac.uk/~tpm40/LAMOST/7500_LAMOST.tar
wget https://www.ast.cam.ac.uk/~tpm40/LAMOST/7750_LAMOST.tar
wget https://www.ast.cam.ac.uk/~tpm40/LAMOST/8000_LAMOST.tar
